### ISSUE TITLE
Buttons not holding

### ISSUE THREAD

**Issue by Zeannn** [PJSoftCo/VGamepad#33]
I can't seem to hold LT LB RT RB buttons, I'm playing GRID Autosport on Ryujinx and i can't hold on the accelerator (RT), buttons like triangles square circle and x seems to hold as the color changes and remains the changed color

**Comment by pjsoftcoUser** [comment]
You mean it doesn't stay pressed while you keep your finger on it? Android or ios?

**Comment by Zeannn** [comment]
> You mean it doesn't stay pressed while you keep your finger on it? Android or ios?

Yes, Im on IOS

**Comment by pjsoftcoUser** [comment]
Square/circle/triangle buttons use the feature called continuous touch which you can switch between them just by moving around your finger around them! But other buttons are stand alone buttons which work like press and release buttons! It still should stay pressed while you keep your finger on it! I'm still not sure what the problem is though! Everything works as expected while i test it. Perhaps providing a video can help understanding the problem!
